### ISSUE TITLE
垃圾

### ISSUE THREAD

**Issue by wangzhihai01** [donho/donho.github.io#3]
你去过中国大陆吗?去过新疆吗?不了解就不要乱逼逼,一点素质都没有!

**Comment by necan** [comment]
这智障的真名叫 侯今吾，是个台独分子，现在拿了法国国籍，是个政治狂热分子，逢中必反，这货 08 年时还一度抵制北京奥运会。

**Comment by Emma990** [comment]
侯今吾，你傻逼东西吃你妈的奶逼水去吧，滚你妈的畜生，操你妈的臭逼！老子把你妈吊起来吊打她的阴道，老子把他妈毛毛虫放进你妈的阴道里面，生出你个杂种，操你妈的臭逼！ 滚！
